# Default values for reportservice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

image:
  repository: reports-service
  pullPolicy: Always

name: reportservice
namespace: sage
imagePullSecret:

spec:
  containers:
    imagePullPolicy: Always
    image:
    ports:
      containerPort:
    volumeMounts:
      name:
  volumes:
    name: reportservice-pv-claim
    persistentVolumeClaim: reportservice-pv-claim
    persistentVolumeClaimStorage:
    storageClass:

keycloak:
  allowed_origins:
  auth_server_url:
  realm:
  resource:

env:
  advisor_reports_dir: /AMaaS/advisor-reports
  advisor_sage_report_url:
  git_local_dir: /AMaaS/gitlab
  git_server:
  git_group:
  git_user: oauth
  git_password: ""
  git_user_email:
  sage_host:
  sage_port:
  sage_protocol: https
  sonarqube_dir: /etc/sonarscanner/bin
  sonar_ipaddr:
  sonar_login: ''
  sonar_password: ' '
  sonar_url:
  sage_url: ''
  windows_protocol:
  windows_port:
  windows_host:
  spring_kafka_bootstrap_servers:

ingress:
  enabled: true
  hosts:
    - sample.com
  # The ingress path. Useful to host metabase on a subpath, such as `/metabase`.
  path: /
  labels:
    # Used to add custom labels to the Ingress
    # Useful if for example you have multiple Ingress controllers and want your Ingress controllers to bind to specific Ingresses
    # traffic: internal
  annotations: {}
    #kubernetes.io/ingress.class: nginx
    #kubernetes.io/tls-acme: "true"
  tls:
    - secretName: tls-sample.com
      hosts:
        - sample.com

istio:
  enabled: true
  hosts: ""
  gateways: istio-ingress/istio-autogenerated-k8s-ingress
  port: 8080
