# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


namespace: sage
name: highlightagent
replicaCount: 4

image:
  repository: highlightagent
  imagePullPolicy: Always

imagePullSecrets: regcred

containers:
  containerPort: 8080
  env:
    git_server: ""
    git_user: oauth
    highlight_username:
    highlight_viewerusername:
    highlight_adminusername:
    git_user_email:
    git_local_dir: /tmp/code/highlight-agent/git-repositories
    git_reports_dir: /tmp/code/highlight-agent/git-repositories/reports
    highlight_url:
    highlight_domain_name:
    highlight_scafeature: true
    highlight_subdomain:
    highlight_user_name:
    highlight_java_dir: /usr/bin
    highlight_command_dir: /opt/hlt
    highlight_reports_dir: /AMaaS/highlight/reports
    highlight_sage_report_url:
    queue_analysis_server:
    sage_server:
    highlight_scan_timeout_minutes:
    highlight_app_timeout_minutes:
    highlight_app3rdparty_timeout_minutes:
    highlight_appdependency_timeout_minutes:
    spring_kafka_bootstrap_servers:
  resources:
    limits:
      cpu: 2
    requests:
      cpu: 1

secret:
  git_user:
  git_password:
  highlight_password:
  highlight_viewerpassword:
  highlight_adminpassword:
volumeMounts:
  mountPath: /AMaaS/highlight/reports
volumes:
  persistentVolumeClaim: highlightagent-pv-claim
  persistentVolumeStorage: 20Gi

service:
  type: ClusterIP
  port: 80

keycloak:
  allowed_origins:
  auth_server_url:
  realm:
  resource:

ingress:
  enabled: true
  hosts:
    - sample.com
  # The ingress path. Useful to host metabase on a subpath, such as `/metabase`.
  path: /
  labels:
    # Used to add custom labels to the Ingress
    # Useful if for example you have multiple Ingress controllers and want your Ingress controllers to bind to specific Ingresses
    # traffic: internal
  annotations: {}
    #kubernetes.io/ingress.class: nginx
    #kubernetes.io/tls-acme: "true"
  tls:
    - secretName: tls-sample.com
      hosts:
        - sample.com

istio:
  enabled: true
  hosts: ""
  port: 80
  gateways: istio-ingress/istio-autogenerated-k8s-ingress
