apiVersion: v2
appVersion: "1.0"
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
  version: 10.14.4
- name: redis
  version: 17.3.17
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
description: Apache Superset is a modern, enterprise-ready business intelligence web
  application
maintainers:
- email: craig@craigrueda.com
  name: craig-rueda
  url: https://github.com/craig-rueda
name: superset
version: 1.1.6
