apiVersion: v2
appVersion: "1.0"
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 10.2.0
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 12.3.3
description: Apache Superset is a modern, enterprise-ready business intelligence web
  application
maintainers:
- email: craig@craigrueda.com
  name: craig-rueda
  url: https://github.com/craig-rueda
name: superset
version: 1.0.0
